name: Test Workflow
on:
  # Trigger on push to main branch
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
          
      - name: Success
        run: echo "Workflow completed successfully!"
